namespace PageParser {
    public enum ResultItem {
        LinksCount = 1,
        InternalLinksCount = 2,
        UniqueInternalLinksCount = 3,
        NorUniqueInternalLinksCount = 4,
        InternalLinksHasImgAnchor= 5,
        HtmlLangValue = 6,
        ImgSrcTagCount = 7,
        TitleTagCount = 8,
        AverageTitleTag = 9,
        StyleBackgroundImageInUrlCount = 10,
        InstagramLinkExist = 11,
        TwitterLinkExist = 12,
        FacebookLinkExist = 13,
        YoutubeLinkExist = 14,
        VkLinkExist = 15,
        GoogleLinkExist = 16,
        H2HeaderCount = 17,
        H3HeaderCount = 18,
        H4HeaderCount = 19,
        H5HeaderCount = 20,
        H6HeaderCount = 21,
        ThisPageIsMain = 22,
        LinksCountWithoutMainPageMatches = 23,
        InternalLinksHasImgAnchorWithoutMainPageMatches = 24,
        ImgSrcTagCountWithoutMainPageMatches = 25,
        TableTagCountWithoutMainPageMatches = 26,
        H2HeaderCountWithoutMainPageMatches = 27,
        H3HeaderCountWithoutMainPageMatches = 28,
        H4HeaderCountWithoutMainPageMatches = 29,
        H5HeaderCountWithoutMainPageMatches = 30,
        H6HeaderCountWithoutMainPageMatches = 31,
    }
}